feat(zotero): search_zotero - exit after pressing alt-z

diff --git a/zotero/.config/Zotero/bin/search_zotero b/zotero/.config/Zotero/bin/search_zotero
--- a/zotero/.config/Zotero/bin/search_zotero
+++ b/zotero/.config/Zotero/bin/search_zotero
@@ -5,7 +5,7 @@
 # Dependencies: zotero netcat fzf
 
 search_entries() {
-  script='
+	script='
   (async function () {
 
   let libraries = await Zotero.Libraries.getAll()
@@ -77,12 +77,12 @@ for (let library of libraries) {
 let result = collections_str
 '
 
-  result="$(eval_script_return_value "$script")"
-  FRE_NAME="zotero_items"
+	result="$(eval_script_return_value "$script")"
+	FRE_NAME="zotero_items"
 
-  frecency_result="$(fre --store_name "zotero_items" --sorted)"
+	frecency_result="$(fre --store_name "zotero_items" --sorted)"
 
-  result="$(awk -F$'\t' '
+	result="$(awk -F$'\t' '
 NR==FNR { order[NR] = $1; next }
 {
     key = $1;
@@ -115,10 +115,10 @@ END {
     }
   }' <(echo "$frecency_result") <(echo "$result"))"
 
-  awk 'NR==1 {print; next} NR%2==0 {printf "%s\0", $0; next} {print}' < <(echo "$result") >|/tmp/result_null
+	awk 'NR==1 {print; next} NR%2==0 {printf "%s\0", $0; next} {print}' < <(echo "$result") >|/tmp/result_null
 
-  # Focus collection and item in Zotero JS
-  focus_zotero_item='(async function() {
+	# Focus collection and item in Zotero JS
+	focus_zotero_item='(async function() {
     function getZoteroPane() {
 		  let windows = Zotero.getMainWindows();
 		  for (let win of windows) {
@@ -136,44 +136,44 @@ END {
 
   focus_zotero_item('
 
-  TMP_FILE="$(mktemp -t "tmp_XXX")"
-  readonly TMP_FILE
+	TMP_FILE="$(mktemp -t "tmp_XXX")"
+	readonly TMP_FILE
 
-  trap 'rm $TMP_FILE' EXIT
+	trap 'rm $TMP_FILE' EXIT
 
-  IFS='' read -r -d '' cmd <<EOF
+	IFS='' read -r -d '' cmd <<EOF
   cat "/tmp/result_null" |  fzf --multi --read0 --ansi --with-nth {5..} \
   --preview='$XDG_CONFIG_HOME/fzf/fzf_preview_media "\$(find {4}  -type f -name "*" ! -name ".*" 2>/dev/null)"'\
   --bind 'alt-u:execute-silent(xdg-open {3})' \
   --bind 'alt-q:execute-silent(dunstify {1})' \
-  --bind 'alt-z:execute-silent(i3-msg '\''[class="Zotero"] focus'\'' && /bin/nc 127.0.0.1 8080 < <(echo "${focus_zotero_item}{1})})();"))' \
+  --bind 'alt-z:execute-silent(i3-msg '\''[class="Zotero"] focus'\'' && /bin/nc 127.0.0.1 8080 < <(echo "${focus_zotero_item}{1})})();"))+abort' \
   --header 'Enter open document, A-u open link, A-z focus in zotero' \
   >| '${TMP_FILE}'
 EOF
 
-  eval_interactive_cmd --floating --geometry 'fullscreen toggle' "$cmd"
+	eval_interactive_cmd --floating --geometry 'fullscreen toggle' "$cmd"
 
-  [[ -s "$TMP_FILE" ]] || exit 1
+	[[ -s "$TMP_FILE" ]] || exit 1
 
-  FILES_PATH="$(<"$TMP_FILE" cut -d $'\t' -f 4 | sed -n 'p;n')"
+	FILES_PATH="$(<"$TMP_FILE" cut -d $'\t' -f 4 | sed -n 'p;n')"
 
-  while IFS= read -r FILE_PATH; do
-    # Open document if directory exists; otherwise, open link
-    if [[ -d "$FILE_PATH" ]]; then
-      xdg-open "$(find "$FILE_PATH" -type f -name "*" ! -name ".*")" &
-      disown
-      i3-msg "workspace --no-auto-back-and-forth 8"
-    else
-      xdg-open "$(<"$TMP_FILE" cut -d $'\t' -f 3 | head -n 1)"
-    fi
-    fre --store_name "$FRE_NAME" --add "$(<"$TMP_FILE" cut -d $'\t' -f -1 | head -n 1)"
-  done <<<"$FILES_PATH"
+	while IFS= read -r FILE_PATH; do
+		# Open document if directory exists; otherwise, open link
+		if [[ -d "$FILE_PATH" ]]; then
+			xdg-open "$(find "$FILE_PATH" -type f -name "*" ! -name ".*")" &
+			disown
+			i3-msg "workspace --no-auto-back-and-forth 8"
+		else
+			xdg-open "$(<"$TMP_FILE" cut -d $'\t' -f 3 | head -n 1)"
+		fi
+		fre --store_name "$FRE_NAME" --add "$(<"$TMP_FILE" cut -d $'\t' -f -1 | head -n 1)"
+	done <<<"$FILES_PATH"
 }
 
 focus_zotero_entry_from_path() {
-  path="$1"
-  file_name="${path##*/}"
-  SCRIPT='
+	path="$1"
+	file_name="${path##*/}"
+	SCRIPT='
 (async function() {
     function getZoteroPane() {
 		  let windows = Zotero.getMainWindows();
@@ -197,39 +197,39 @@ focus_zotero_entry_from_path() {
   await focus_zotero_item();
 })();
 '
-  nc 127.0.0.1 8080 < <(echo "$SCRIPT")
+	nc 127.0.0.1 8080 < <(echo "$SCRIPT")
 }
 
 eval_script_return_value() {
-  tmp="/tmp/search_zotero_${RANDOM}"
+	tmp="/tmp/search_zotero_${RANDOM}"
 
-  SCRIPT='
+	SCRIPT='
   '"$1"'
   await Zotero.File.putContentsAsync("'"$tmp"'", result);
 })();
 '
 
-  nc 127.0.0.1 8080 < <(echo "$SCRIPT")
-  until [[ -f "$tmp" ]]; do
-    sleep 0.1
-  done
-  cat "$tmp"
-  rm "$tmp"
+	nc 127.0.0.1 8080 < <(echo "$SCRIPT")
+	until [[ -f "$tmp" ]]; do
+		sleep 0.1
+	done
+	cat "$tmp"
+	rm "$tmp"
 }
 
 if ! pgrep zotero >/dev/null; then
-  nohup zotero >/dev/null 2>&1 &
-  disown
-  until nc -zv 127.0.0.1 8080 >/dev/null 2>&1; do
-    sleep 0.1
-  done
-  i3-msg '[class="Zotero"] move scratchpad'
-  sleep 1
+	nohup zotero >/dev/null 2>&1 &
+	disown
+	until nc -zv 127.0.0.1 8080 >/dev/null 2>&1; do
+		sleep 0.1
+	done
+	i3-msg '[class="Zotero"] move scratchpad'
+	sleep 1
 fi
 
 if (($# == 0)); then
-  search_entries
+	search_entries
 else
-  i3-msg '[class="Zotero"] move workspace current, focus'
-  focus_zotero_entry_from_path "$1"
+	i3-msg '[class="Zotero"] move workspace current, focus'
+	focus_zotero_entry_from_path "$1"
 fi
