feat(zotero): add search_zotero to zotero_utility

diff --git a/zotero/.config/Zotero/bin/zotero_utility b/zotero/.config/Zotero/bin/zotero_utility
--- a/zotero/.config/Zotero/bin/zotero_utility
+++ b/zotero/.config/Zotero/bin/zotero_utility
@@ -2,9 +2,11 @@
 # Zotero utility:
 # - Import to zotero from various sources to a collection
 # - Get a paper's DOI or title
+# - Search for papers
+# - Focus entry in zotero
 #
 # Arguments:
-#   zotero_utility [import|get_metadata] args
+#   zotero_utility [import|get_metadata|search|focus_entry] args
 #
 #   import:
 #   --collection_name <collection_name>: Colletion name (optional)
@@ -12,9 +14,12 @@
 #   --recent: Import to the collection that was imported before (optional)
 #   <SOURCE>: URL or path to paper
 #
-#   get_metadata :
+#   get_metadata:
 #   $1: [DOI|title]
-#   $2; SOURCE: URL or path to paper
+#   $2: SOURCE: URL or path to paper
+#
+#   focus_entry:
+#   $1: File path
 #
 # Dependencies: zotero, netcat
 
@@ -254,25 +259,6 @@ async function waitForCondition(conditionFn, timeoutMs, pollIntervalMs = 100) {
 	fi
 }
 
-eval_script_return_value() {
-	TMP_FILE2="/tmp/zotero_return_value"
-
-	rm -f "$TMP_FILE2"
-	trap 'rm -f $TMP_FILE2' RETURN
-
-	local -r SCRIPT='
-	'"$1"'
-	await Zotero.File.putContentsAsync("'"$TMP_FILE2"'", result);
-	})();
-	'
-
-	nc 127.0.0.1 8080 < <(echo "$SCRIPT")
-	until [[ -f "$TMP_FILE2" ]]; do
-		sleep 0.1
-	done
-	cat "$TMP_FILE2"
-}
-
 get_metadata() {
 
 	if [[ "$1" != "DOI" && "$1" != "title" ]]; then
@@ -380,14 +366,242 @@ get_metadata() {
 	eval_script_return_value "$SCRIPT"
 }
 
+search_entries() {
+	script='
+  (async function () {
+
+  let libraries = await Zotero.Libraries.getAll()
+
+  let collections_str = ""
+  let items_str = ""
+  let storage_path = Zotero.getStorageDirectory().path
+
+  function get_collections(collections, name) {
+
+  for (let collection of collections) {
+    if (collection.hasChildCollections()) {
+      collections_str += collection.key + "\t" + name + " > " + collection.name
+      get_collections(collection.getChildCollections(), name + " > " + collection.name)
+    } else {
+    collections_str += collection.key + "\t" + name + " > " + collection.name
+  }
+
+  if (collection.hasChildItems()) {
+
+    collection_path = name + " > " + collection.name
+    collection.getChildItems().forEach(function (item) {
+    let item_json = item.toJSON();
+    let file_path = "null"
+    let url = "null"
+    let date = ""
+    let creators = ""
+    //file_path = Zotero.Attachments.getStorageDirectory(item).path
+    if (item._bestAttachmentState != null) {
+      if (item._bestAttachmentState.exists && item._bestAttachmentState.type === "pdf") {
+        file_path = storage_path + "/" + item._bestAttachmentState.key
+      }
+    } else if (item._attachments !=null) {
+    if (item._attachments.rows.length > 0) {
+    for (let row of item._attachments.rows) {
+      file_path = Zotero.Attachments.getStorageDirectoryByID(row.itemID).path
+    }
+  }
+}
+    if ("url" in item_json) {
+      url = item_json.url
+    }
+
+    if ("date" in item_json) {
+      date = item_json.date
+    }
+
+    if (item_json.creators.length > 0) {
+      item_json.creators.forEach(function(creator) {
+      creators += creator.firstName + " " + creator.lastName + ", ";
+      } );
+      creators = creators.substring(0, creators.length -2);
+    }
+
+    items_str += item._id + "\t" + item_json.key + "\t" + url + "\t" + file_path + "\t" + collection_path + "\t" + item_json.itemType + "\t" + date + "\t" + creators + "\n" + item_json.title + "\n"
+  });
+}
+}
+return items_str
+}
+
+let collections = await Zotero.Collections.getLoaded()
+
+for (let library of libraries) {
+  let collections = await Zotero.Collections.getByLibrary(library.id)
+  collections_str += get_collections(collections, library.name)
+}
+
+let result = collections_str
+'
+
+	result="$(eval_script_return_value "$script")"
+	FRE_NAME="zotero_items"
+
+	frecency_result="$(fre --store_name "zotero_items" --sorted)"
+
+	result="$(awk -F$'\t' '
+NR==FNR { order[NR] = $1; next }
+{
+    key = $1;
+    val = $1 "\t" $2 "\t" $3 "\t" $4 "\t\033[36m" $5 "\033[0m\t\033[1;38m" $6 "\033[0m\t\033[37m" $7 "\t" $8 "\033[0m" ;
+    getline;
+    val = val ORS "\033[1;32m" $0 "\033[0m";
+    data[key] = val;
+    keys[++count] = key;
+}
+END {
+    # Print keys that exist in `a` first, in order
+
+    for (k in order) {
+        i=order[k];
+        if (i in data) print data[i];
+    }
+    # Print remaining keys in their original order
+    not_found = 1
+    for (i = 1; i <= count; i++) {
+        not_found = 1
+        for (k in order) {
+            if (order[k] == keys[i]) {
+                not_found = 0
+                break;
+            }
+        }
+        if (not_found) {
+            print data[keys[i]]
+        }
+    }
+  }' <(echo "$frecency_result") <(echo "$result"))"
+
+	awk 'NR==1 {print; next} NR%2==0 {printf "%s\0", $0; next} {print}' < <(echo "$result") >|/tmp/result_null
+
+	# Focus collection and item in Zotero JS
+	focus_zotero_item='(async function() {
+    function getZoteroPane() {
+		  let windows = Zotero.getMainWindows();
+		  for (let win of windows) {
+			  if (win.ZoteroPane) return win.ZoteroPane
+		  }
+	  }
+    async function focus_zotero_item(id) {
+      let item = Zotero.Items.get(id)
+      let zotero_pane = getZoteroPane();
+      // Focus collection
+      await zotero_pane.collectionsView.selectCollection(item._collections[0])
+      // Focus item
+      zotero_pane.selectItem(item._id)
+    }
+
+  focus_zotero_item('
+
+	TMP_FILE="$(mktemp -t "tmp_XXX")"
+	readonly TMP_FILE
+
+	trap 'rm $TMP_FILE' EXIT
+
+	IFS='' read -r -d '' cmd <<EOF
+  cat "/tmp/result_null" |  fzf --multi --read0 --ansi --with-nth {5..} \
+  --preview='$XDG_CONFIG_HOME/fzf/fzf_preview_media "\$(find {4}  -type f -name "*" ! -name ".*" 2>/dev/null)"'\
+  --bind 'alt-u:execute-silent(xdg-open {3})' \
+  --bind 'alt-q:execute-silent(dunstify {1})' \
+  --bind 'alt-z:execute-silent(i3-msg '\''${ZOTERO_CONDITION} focus'\'' && /bin/nc 127.0.0.1 8080 < <(echo "${focus_zotero_item}{1})})();"))+abort' \
+  --header 'Enter open document, A-u open link, A-z focus in zotero' \
+  >| '${TMP_FILE}'
+EOF
+
+	eval_interactive_cmd --floating --geometry 'fullscreen toggle' "$cmd"
+
+	[[ -s "$TMP_FILE" ]] || exit 1
+
+	FILES_PATH="$(<"$TMP_FILE" cut -d $'\t' -f 4 | sed -n 'p;n')"
+
+	while IFS= read -r FILE_PATH; do
+		# Open document if directory exists; otherwise, open link
+		if [[ -d "$FILE_PATH" ]]; then
+			xdg-open "$(find "$FILE_PATH" -type f -name "*" ! -name ".*")" &
+			disown
+			i3-msg "workspace --no-auto-back-and-forth 8"
+		else
+			xdg-open "$(<"$TMP_FILE" cut -d $'\t' -f 3 | head -n 1)"
+		fi
+		fre --store_name "$FRE_NAME" --add "$(<"$TMP_FILE" cut -d $'\t' -f -1 | head -n 1)"
+	done <<<"$FILES_PATH"
+}
+
+focus_zotero_entry_from_path() {
+	path="$1"
+	file_name="${path##*/}"
+
+	i3-msg "$ZOTERO_CONDITION move workspace current, focus"
+	SCRIPT='
+(async function() {
+    function getZoteroPane() {
+		  let windows = Zotero.getMainWindows();
+		  for (let win of windows) {
+			  if (win.ZoteroPane) return win.ZoteroPane
+		  }
+	  }
+
+    async function focus_zotero_item() {
+      rows = await Zotero.DB.queryAsync("SELECT itemID, path FROM itemAttachments WHERE path LIKE ? ", [`storage:'"${file_name}"'`])
+      id = rows[0].itemID;
+      let attachmentItem = await Zotero.Items.get(id)
+      entryItem = attachmentItem.parentItem
+      let zotero_pane = getZoteroPane();
+      // Focus collection
+      await zotero_pane.collectionsView.selectCollection(entryItem._collections[0])
+      // Focus item
+      zotero_pane.selectItem(entryItem._id)
+    }
+
+  await focus_zotero_item();
+})();
+'
+	nc 127.0.0.1 8080 < <(echo "$SCRIPT")
+}
+
+eval_script_return_value() {
+	tmp="/tmp/search_zotero_${RANDOM}"
+
+	SCRIPT='
+  '"$1"'
+  await Zotero.File.putContentsAsync("'"$tmp"'", result);
+})();
+'
+
+	nc 127.0.0.1 8080 < <(echo "$SCRIPT")
+
+	# Send script again, if Zotero doesn't respond
+	local TIMEOUT=2 START=$SECONDS FLAG="false"
+
+	until [[ -f "$tmp" ]]; do
+		[[ "$FLAG" != "true" ]] && ((SECONDS - START >= TIMEOUT)) && nc 127.0.0.1 8080 < <(echo "$SCRIPT") && FLAG="true"
+		sleep 0.1
+	done
+	cat "$tmp"
+	rm "$tmp"
+}
+
 main() {
-	if ! pgrep zotero >/dev/null; then
+	source "$HOME/.bashrc.d/functions.bash"
+
+	# Open Zotero
+	if ! is_window_exists "^Zotero$"; then
 		nohup zotero >/dev/null 2>&1 &
 		disown
+		wait_window "^Zotero$"
+		ZOTERO_CONDITION="$(window_get_condition "^Zotero$")"
 		until nc -zv 127.0.0.1 8080 >/dev/null 2>&1; do
 			sleep 0.1
 		done
-		i3-msg '[class="Zotero"] move scratchpad' >/dev/null
+		sleep 2
+		i3-msg "$ZOTERO_CONDITION move scratchpad"
+	else
+		ZOTERO_CONDITION="$(window_get_condition "^Zotero$")"
 	fi
 
 	case $1 in
@@ -398,6 +612,13 @@ main() {
 		get_metadata)
 			shift
 			get_metadata "$@"
+			;;
+		search)
+			search_entries
+			;;
+		focus_entry)
+			shift
+			focus_zotero_entry_from_path "$@"
 			;;
 		*)
 			dunstify "$1 utlity isn't supported" && exit 1
