updates (mailcap mpv, i3 startup) and fixes (pinentry emacs, git-sync, cron)

diff --git a/qutebrowser/.config/qutebrowser/userscripts/open_download b/qutebrowser/.config/qutebrowser/userscripts/open_download
--- a/qutebrowser/.config/qutebrowser/userscripts/open_download
+++ b/qutebrowser/.config/qutebrowser/userscripts/open_download
@@ -1,60 +1,9 @@
 #!/usr/bin/env bash
-# Both standalone script and qutebrowser userscript that opens a rofi menu with
-# all files from the download directory and opens the selected file. It works
-# both as a userscript and a standalone script that is called from outside of
-# qutebrowser.
-#
-# Suggested keybinding (for "show downloads"):
-# spawn --userscript ~/.config/qutebrowser/open_download
-#     sd
-#
-# Requirements:
-#  - rofi (in a recent version)
-#  - xdg-open and xdg-mime
-#  - You should configure qutebrowser to download files to a single directory
-#  - It comes in handy if you enable downloads.remove_finished. If you want to
-#    see the recent downloads, just press "sd".
-#
-# Thorsten Wißmann, 2015 (thorsten` on Libera Chat)
-# Any feedback is welcome!
 
-set -e
+# Use rofi in qutebrowser to delete/open (most recent) downloaded files
+# Dependencies: rofi, xdg-open and xdg-mime
 
-# open a file from the download directory using rofi
-DOWNLOAD_DIR=${DOWNLOAD_DIR:-$QUTE_DOWNLOAD_DIR}
-DOWNLOAD_DIR=${DOWNLOAD_DIR:-$HOME/Downloads}
-# the name of the rofi command
-ROFI_CMD=${ROFI_CMD:-rofi}
-ROFI_ARGS=${ROFI_ARGS:-}
-
-msg() {
-    local cmd="$1"
-    shift
-    local msg="$*"
-    if [ -z "$QUTE_FIFO" ] ; then
-        echo "$cmd: $msg" >&2
-    else
-        echo "message-$cmd \"${msg}\"" >> "$QUTE_FIFO"
-    fi
-}
-die() {
-    msg error "$*"
-    if [ -n "$QUTE_FIFO" ] ; then
-        # when run as a userscript, the above error message already informs the
-        # user about the failure, and no additional "userscript exited with status
-        # 1" is needed.
-        exit 0;
-    else
-        exit 1;
-    fi
-}
-
-if ! [ -d "$DOWNLOAD_DIR" ] ; then
-    die "Download directory »$DOWNLOAD_DIR« not found!"
-fi
-if ! command -v "${ROFI_CMD}" > /dev/null ; then
-    die "Rofi command »${ROFI_CMD}« not found in PATH!"
-fi
+message () { echo "message-info ${1@Q}" >> "$QUTE_FIFO"; }
 
 rofi_default_args=(
         -monitor -2 # place above window
@@ -66,57 +15,75 @@ rofi_default_args=(
         -l 10
         -p 'Open download' -dmenu
     )
+download_dir=${QUTE_DOWNLOAD_DIR:-$HOME/Downloads}
+rofi_cmd="rofi"
+declare -a files
 
-crop-first-column() {
-    local maxlength=${1:-40}
-    local expression='s|^\([^\t]\{0,'"$maxlength"'\}\)[^\t]*\t|\1\t|'
-    sed "$expression"
-}
+# Handle options
+# recent: If it exists, act of most recent file, otherwise let the user choose
+# delete: If it exists, delete the file, otherwise open it
+long_opts=delete,recent
+opts=dr
+parsed=$(getopt --options=$opts --longoptions=$long_opts --name "$0" -- "$@")
 
-ls-files() {
-    # add the slash at the end of the download dir enforces to follow the
-    # symlink, if the DOWNLOAD_DIR itself is a symlink
-    # shellcheck disable=SC2010
-    ls -Q --quoting-style escape    -h  -o -1 -A -t "${DOWNLOAD_DIR}/" \
-        | grep '^[-]' \
-        | cut -d' ' -f3- \
-        | sed 's,^\(.*[^\]\) \(.*\)$,\2\t\1,' \
-        | sed 's,\\\(.\),\1,g'
-}
+[[ $? -ne 0 ]] && exit 1 # exit when the option is unknown
 
-mapfile -t entries < <(ls-files)
+# Update positional arguments with getopt results,
+# i.e. placing operands after "--" to deal with them later
+eval set -- "$parsed"
 
-# we need to manually check that there are items, because rofi doesn't show up
-# if there are no items and -no-custom is passed to rofi.
-if [ "${#entries[@]}" -eq 0 ] ; then
-    die "Download directory »${DOWNLOAD_DIR}« empty"
-fi
+is_delete= is_recent=
+while : ; do
+    case "$1" in
+        -d|--delete) is_delete=1; shift ;;
+        -r|--recent) is_recent=1; shift ;;
+        --) shift; break ;;
+        *) echo "Programming error"; exit 3 ;;
+    esac
+done
 
-parsed_lines=$(printf '%s\n' "${entries[@]}"  \
-       | crop-first-column 55 \
-       | column -s $'\t' -t)
+# Test existance of directory and command
+[[ ! -d "$download_dir" ]] \
+    && message "Download directory $download_dir is not found!" && exit 0
+! command -v "$rofi_cmd" > /dev/null \
+    && message "$rofi_cmd command is not found in PATH" && exit 0
 
-if [[ $1 == "--recent" ]]; then
+# Store files sorted by modification time in an array
+while IFS=$'\0' read -r -d ''; do
+  files+=("$(basename "$REPLY")")
+done < <(find "$download_dir" -type f -printf '%Ts %p\0' | cut -z -d " " -f 2- )
+
+[[ "${#files[@]}" -eq 0 ]] \
+    && message "Download directory $download_dir is empty" && exit 0
+
+# Open the most recent file or the chosen one
+if [[ $is_recent ]]; then
     chosen_line=0
 else
-    chosen_line=$(echo "$parsed_lines" | $ROFI_CMD "${rofi_default_args[@]}" $ROFI_ARGS) || true
+    chosen_line="$(printf "%s\n" "${files[@]}" | $rofi_cmd "${rofi_default_args[@]}")" || echo $'\0'
 fi
 
-if [ -z "$chosen_line" ];  then
-    exit 0
-fi
-echo "$chosen_line"
+# No file was chosen; i.e. NULL value
+[[ ! "$chosen_line" ]] && exit 0
 
-file="${entries[$chosen_line]}"
-file="${file%%$'\t'*}"
-path="$DOWNLOAD_DIR/$file"
+file="${files[$chosen_line]}"
+path="${download_dir}/${file}"
+
+# Delete the file and exit
+[[ $is_delete ]] && {
+    rm "$path";
+    message "${file@Q} is Deleted" && exit 0
+}
+# Otherwise open it
+
 filetype=$(xdg-mime query filetype "$path")
 application=$(xdg-mime query default "$filetype")
 
-if [ -z "$application" ] ; then
-    die "Do not know how to open »$file« of type $filetype"
-fi
+[[ -z "$application" ]] \
+    && message "Can't open $file of type $filetype" && exit 0
 
-msg "info" "Opening $file"
+message "Opening $file"
 
 xdg-open "$path" &
+
+exit 0
