feat: minor changes and disabled magit-delta for the time being until it's fixed

diff --git a/qutebrowser/.config/qutebrowser/userscripts/qute_org_capture b/qutebrowser/.config/qutebrowser/userscripts/qute_org_capture
--- a/qutebrowser/.config/qutebrowser/userscripts/qute_org_capture
+++ b/qutebrowser/.config/qutebrowser/userscripts/qute_org_capture
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
-~/.config/i3/set_i3_focus_on_window_activation_configuration none
+$XDG_CONFIG_HOME/i3/set_i3_focus_on_window_activation_configuration none
 emacsclient --no-wait "org-protocol://capture?url=$QUTE_URL&title=$QUTE_TITLE"
-sleep 0.5
-~/.config/i3/set_i3_focus_on_window_activation_configuration smart
 
-echo ":message-info 'Note captured'" >> $QUTE_FIFO
+if (( $? == 0 )); then
+    echo ":message-info 'Note captured'" >> $QUTE_FIFO
+    $XDG_CONFIG_HOME/i3/set_i3_focus_on_window_activation_configuration smart
+else
+    echo ":message-error 'Note not captured'" >> $QUTE_FIFO
+fi
diff --git a/scripts/bin/wait_internet b/scripts/bin/wait_internet
--- a/scripts/bin/wait_internet
+++ b/scripts/bin/wait_internet
@@ -1,17 +1,19 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
-# wait for internet connection or 5 iterations
+# Description: Wait for internet connection or <COUNT> seconds
+# Dependencies: wget
+# Note: Can get rid of this Dependency if needed with other options, check:
+# https://stackoverflow.com/questions/929368/how-to-test-an-internet-connection-with-bash
 
-wget -q --spider http://google.com
-RESULT=$?
+COUNT=5
 
-COUNT=0
-
-until [ $COUNT -eq 5 ] || [ $RESULT -eq 0 ]; do
+until wget -q --spider http://google.com || [ $COUNT = 0 ]; do
     sleep 1
-    ((COUNT+=1))
-    wget -q --spider http://google.com
-    RESULT=$?
+    COUNT=$((COUNT-1))
 done
 
-exit $RESULT
+# Make sure that the count isn't 0 by using exit status
+[ $COUNT != 0 ]
+
+# No need for double quotes, since we need a number
+exit $?
