feat(qute): address uncompleted selections in yank highlighs

diff --git a/qutebrowser/.config/qutebrowser/userscripts/yank_url_with_highlighted_text b/qutebrowser/.config/qutebrowser/userscripts/yank_url_with_highlighted_text
--- a/qutebrowser/.config/qutebrowser/userscripts/yank_url_with_highlighted_text
+++ b/qutebrowser/.config/qutebrowser/userscripts/yank_url_with_highlighted_text
@@ -23,18 +23,27 @@ encode_url() {
 SELECTED_TEXT="$QUTE_SELECTED_TEXT"
 MAX_WORDS=6
 
-if (($(wc -w <<<"${SELECTED_TEXT}") > MAX_WORDS)); then
+[[ "$SELECTED_TEXT" ]] || { echo "message-error 'No text is selected'" >>"$QUTE_FIFO" && exit 0; }
 
-	FIRST_PORTION="$(echo "$SELECTED_TEXT" | cut -d ' ' -f -3)"
+COMPLETE_SELECTED_TEXT="$(grep -o -m 1 "[^ ]*${SELECTED_TEXT}[^ ]*" <"$QUTE_TEXT")"
+
+# Trim leading spaces
+TRIMMED_SELECTED_TEXT=${COMPLETE_SELECTED_TEXT#"${COMPLETE_SELECTED_TEXT%%[![:space:]]*}"}
+# Trim trailing spaces
+TRIMMED_SELECTED_TEXT=${TRIMMED_SELECTED_TEXT%"${TRIMMED_SELECTED_TEXT##*[![:space:]]}"}
+
+if (($(wc -w <<<"${TRIMMED_SELECTED_TEXT}") > MAX_WORDS)); then
+
+	FIRST_PORTION="$(echo "$TRIMMED_SELECTED_TEXT" | head -1 | cut -d ' ' -f -$((MAX_WORDS / 2)))"
 	ENCODED_FIRST_PORTION="$(encode_url "$FIRST_PORTION")"
 
-	SECOND_PORTION="$(echo "$SELECTED_TEXT" | rev | cut -d ' ' -f -3 | rev)"
+	SECOND_PORTION="$(echo "$TRIMMED_SELECTED_TEXT" | tail -1 | rev | cut -d ' ' -f -$((MAX_WORDS / 2)) | rev)"
 	ENCODED_SECOND_PORTION="$(encode_url "$SECOND_PORTION")"
 
 	# "," is needed to include the text between the portions
 	ENCODED_SELECTED_TEXT="${ENCODED_FIRST_PORTION},${ENCODED_SECOND_PORTION}"
 else
-	ENCODED_SELECTED_TEXT="$(encode_url "${SELECTED_TEXT}")"
+	ENCODED_SELECTED_TEXT="$(encode_url "${TRIMMED_SELECTED_TEXT}")"
 fi
 
 URL_WITH_NO_ANCHOR="$(echo "${QUTE_URL}" | cut -d '#' -f -1)"
